vim.o.number = true
vim.o.relativenumber = true
vim.o.foldmethod = "indent"
vim.o.foldlevelstart = 99
vim.o.scrolloff = 5
vim.o.sidescrolloff = 4
vim.o.cursorline = true
vim.o.cursorcolumn = true
vim.o.compatible = false
vim.o.hidden = true
vim.o.showmatch = true
vim.o.autochdir = true
vim.o.list = true
vim.o.mouse = "a"
vim.o.mousemodel = "popup_setpos"
vim.o.shortmess = vim.o.shortmess .. 'c'
vim.o.whichwrap = vim.o.whichwrap .. '<,>,h,l'
vim.o.autowrite = true
vim.o.autoread = true
vim.o.confirm = true
vim.o.swapfile = false
vim.o.backup = false
vim.o.writebackup = false
vim.opt.signcolumn = "yes"
vim.o.background = "dark"
vim.o.termguicolors = true
vim.o.encoding = "utf-8"
vim.o.smartindent = true
vim.o.tabstop = 4
vim.o.shiftwidth = 4
vim.o.softtabstop = 4
vim.o.expandtab = true
vim.o.wildignore = "log/**,node_modules/**,target/**,tmp/**,*.rbc"
vim.o.wildmenu = true
vim.o.wildmode = "longest,list,full"
vim.o.hlsearch = true
vim.o.incsearch = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.cmd [[
    autocmd BufEnter * if 0 == len(filter(range(1, winnr('$')), 'empty(getbufvar(winbufnr(v:val), "&bt"))')) | qa! | endif
]]
vim.o.conceallevel = 2
vim.o.pumblend = 20
vim.o.virtualedit = "block"
vim.o.backspace = "2"
vim.o.timeoutlen = 100
vim.g.python3_host_skip_check = 1
vim.o.updatetime = 100
